services:
  tfc1:
    image: gameservermanagers/gameserver:tfc
    container_name: tfc1
    restart: unless-stopped
    networks:
      - tfc1_network
    volumes:
      - ./servers/tfc1:/data
      - ./scripts:/scripts
      - ./config:/config
      - ./plugins:/plugins
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
      - "27005:27005/udp"

networks:
  tfc1_network:
